/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CivicRouteImport } from './routes/civic'
import { Route as IndexRouteImport } from './routes/index'

const CivicRoute = CivicRouteImport.update({
  id: '/civic',
  path: '/civic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/civic': typeof CivicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/civic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/civic'
  id: '__root__' | '/' | '/civic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CivicRoute: typeof CivicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/civic': {
      id: '/civic'
      path: '/civic'
      fullPath: '/civic'
      preLoaderRoute: typeof CivicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CivicRoute: CivicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
